### ISSUE TITLE
Where did the officeCodes come from

### ISSUE THREAD

**Issue by avifo** [JonHenningsson/swembassy#1]
Hello, 

I am trying to repurpose this code to also work with the Swedish embassy in London and was wondering where you found the office codes in the **officeCodes** variable. 

Thanks

**Comment by JonHenningsson** [comment]
It's taken from the booking links on this page: https://www.swedenabroad.se/en/about-abroad-for-swedish-citizens/usa/service-for-swedish-citizens/passports/passports-for-adults/

i.e.

https://www.migrationsverket.se/ansokanbokning/valjtyp?enhet=U1075&sprak=en&callback=http://www.swedenabroad.com/en-GB/Embassies/Washington/Services-for-Swedes/Passport-Applications-and-Name-Registration/

This page contains a link with the code for London: https://www.swedenabroad.se/en/about-abroad-for-swedish-citizens/united-kingdom/service-to-swedish-citizens/passport-abroad/checklist-passportid-card-applications-adults/

https://www.migrationsverket.se/ansokanbokning/valjtyp?enhet=U0586&sprak=sv&callback=https://www.swedenabroad.se
